name: CI

on: [push]

jobs:
  Install:
    if: "!contains(github.event.head_commit.message, 'WIP')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: package.json
      - run: pnpm i --frozen-lockfile

  Test:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: package.json
      - run: pnpm i --frozen-lockfile
      - run: pnpm test

  Lint:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: package.json
      - run: pnpm i --frozen-lockfile
      - run: pnpm run lint

  Mutation:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: package.json
      - run: pnpm i --frozen-lockfile
      - run: pnpm run test:mutation

  Build:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build

  Versioning:
    needs: [Build, Test, Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
