name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    branches: [ "renovate/**" ]

jobs:
  Install:
    if: "!contains(github.event.head_commit.message, 'WIP')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci

  Test:
    needs: Install
    if: "!contains(github.event.head_commit.message, 'WIP')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - run: npm test

  Integration:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - run: cp .env.test .env
      - run: npm run test:integration

  Lint:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - run: npm run lint

  Mutation:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - run: npm run test:mutation

  Build:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run build

  Versioning:
    needs: [Build, Test, Integration, Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          manifest-file: .release-please-manifest.json
