name: CI

on: [pull_request]

jobs:
  Install:
    if: "!contains(github.event.head_commit.message, 'WIP')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci

  Test:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - run: npm test

  Lint:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - run: npm run lint

  Mutation:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - run: npm run test:mutation

  Build:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run build

  Versioning:
    needs: [Build, Test, Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
