name: Mise en production

on:
  workflow_dispatch:

jobs:
  terraform:
    # uses: DNUM-SocialGouv/1j1s-front/.github/workflows/terraform-template.yml@main
    uses: ./.github/workflows/opentofu-template.yml
    secrets: inherit
    with:
      apply: true
      environnement_name: scalingo-production
      environnement_url: https://www.1jeune1solution.gouv.fr
    concurrency: terraform-state-production # Evite les conflits sur le state Terraform

  scalingo:
    name: Déployer le code sur Scalingo
    needs: [terraform]
    runs-on: ubuntu-latest
    environment:
      name: scalingo-production
      url: https://www.1jeune1solution.gouv.fr
    steps:
      - name: Configurer la CLI Scalingo
        uses: scalingo-community/setup-scalingo@v0.1.1
        with:
          api_token: ${{ secrets.SCALINGO_API_TOKEN }}
          region: ${{ vars.SCALINGO_REGION }}
          app_name: ${{ secrets.TF_VAR_NOM_DE_L_APPLICATION }}
      - name: Déployer le code sur Scalingo
        run: |
          scalingo integration-link-manual-deploy main
